---
- hosts: localhost
  connection: local

   environment:
    AWS_ACCESS_KEY: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

  roles:
  # mv local-setup to pretasks
    - local-setup
    - aws-baseenv